export const messages = [
  {
    id: 1,
    english: "Close all tabs",
    persian: "بستن همه تب ها",
    arabic: "إغلاق كل علامات التبويب",
    spanish: "Cerrar todas las pestañas",
    french: "Fermer toutes les onglets",
    turkish: "Tüm sekmeleri kapat",
    portugess: "Fechar todas as guias",
    dutch: "Sluit alle tabbladen",
    russian: "Закрыть все вкладки",
    italian: "Chiudi tutte le schede",
    hindi: "सभी टैब बंद करें",
    urdu: "تمام ٹیبز بند کریں",
    chiness: "关闭所有选项卡",
    japaness: "すべてのタブを閉じる",
    korean: "모든 탭 닫기",
    thai: "ปิดแท็บทั้งหมด",
    malay: "Tutup semua tab",
    indonesian: "Tutup semua tab",
  },
  {
    id: 2,
    english: "Close other tabs",
    persian: "بستن تب های دیگر",
    arabic: "إغلاق علامات التبويب الأخرى",
    spanish: "Cerrar otras pestañas",
    french: "Fermer les autres onglets",
    turkish: "Diğer sekmeleri kapat",
    portugess: "Fechar outras guias",
    dutch: "Sluit andere tabbladen",
    russian: "Закрыть другие вкладки",
    italian: "Chiudi altre schede",
    hindi: "अन्य टैब बंद करें",
    urdu: "دیگر ٹیبز بند کریں",
    chiness: "关闭其他选项卡",
    japaness: "他のタブを閉じる",
    korean: "다른 탭 닫기",
    thai: "ปิดแท็บอื่น",
    malay: "Tutup tab lain",
    indonesian: "Tutup tab lain",
  },
  {
    id: 3,
    english: "Close all next tabs",
    persian: "بستن همه تب های بعدی",
    arabic: "إغلاق جميع علامات التبويب التالية",
    spanish: "Cerrar todas las siguientes pestañas",
    french: "Fermer toutes les prochaines onglets",
    turkish: "Tüm sonraki sekmeleri kapat",
    portugess: "Fechar todas as próximas guias",
    dutch: "Sluit alle volgende tabbladen",
    russian: "Закрыть все следующие вкладки",
    italian: "Chiudi tutte le schede successive",
    hindi: "सभी अगले टैब बंद करें",
    urdu: "تمام آئندہ ٹیبز بند کریں",
    chiness: "关闭所有下一个选项卡",
    japaness: "すべての次のタブを閉じる",
    korean: "모든 다음 탭 닫기",
    thai: "ปิดแท็บต่อไปทั้งหมด",
    malay: "Tutup semua tab seterusnya",
    indonesian: "Tutup semua tab seterusnya",
  },
  {
    id: 4,
    english: "Close all previous tabs",
    persian: "بستن همه تب های قبلی",
    arabic: "إغلاق جميع علامات التبويب السابقة",
    spanish: "Cerrar todas las pestañas anteriores",
    french: "Fermer toutes les onglets précédents",
    turkish: "Tüm önceki sekmeleri kapat",
    portugess: "Fechar todas as guias anteriores",
    dutch: "Sluit alle vorige tabbladen",
    russian: "Закрыть все предыдущие вкладки",
    italian: "Chiudi tutte le schede precedenti",
    hindi: "सभी पिछले टैब बंद करें",
    urdu: "تمام ماضی ٹیبز بند کریں",
    chiness: "关闭所有以前的选项卡",
    japaness: "すべての前のタブを閉じる",
    korean: "모든 이전 탭 닫기",
    thai: "ปิดแท็บก่อนหน้านี้ทั้งหมด",
    malay: "Tutup semua tab sebelumnya",
    indonesian: "Tutup semua tab sebelumnya",
  },
  {
    id: 5,
    english: "Serach ...",
    persian: "جستجو ...",
    arabic: "بحث ...",
    spanish: "Buscar ...",
    french: "Chercher ...",
    turkish: "Arama ...",
    portugess: "Procurar ...",
    dutch: "Zoeken ...",
    russian: "Поиск ...",
    italian: "Ricerca ...",
    hindi: "खोज ...",
    urdu: "تلاش کریں ...",
    chiness: "搜索 ...",
    japaness: "検索 ...",
    korean: "검색 ...",
    thai: "ค้นหา ...",
    malay: "Cari ...",
    indonesian: "Cari ...",
  },
  {
    id: 6,
    english: "Show tabs",
    persian: "نمایش تب ها",
    arabic: "عرض علامات التبويب",
    spanish: "Mostrar pestañas",
    french: "Afficher les onglets",
    turkish: "Sekmeleri göster",
    portugess: "Mostrar guias",
    dutch: "Tabbladen weergeven",
    russian: "Показать вкладки",
    italian: "Mostra schede",
    hindi: "टैब दिखाएं",
    urdu: "ٹیب دکھائیں",
    chiness: "显示选项卡",
    japaness: "タブを表示",
    korean: "탭 표시",
    thai: "แสดงแท็บ",
    malay: "Tunjukkan tab",
    indonesian: "Tunjukkan tab",
  },
  {
    id: 7,
    english: "Back",
    persian: "بازگشت",
    arabic: "عودة",
    spanish: "Espalda",
    french: "Arrière",
    turkish: "Geri",
    portugess: "Costas",
    dutch: "Terug",
    russian: "Назад",
    italian: "Indietro",
    hindi: "वापस",
    urdu: "پیچھے",
    chiness: "背部",
    japaness: "バック",
    korean: "뒤로",
    thai: "กลับ",
    malay: "Kembali",
    indonesian: "Kembali",
  },
];
